### ISSUE TITLE
Changes for secrets manager

### ISSUE THREAD

**Issue by acursons** [ibm-cloud-docs/vpc#113]
The page

https://cloud.ibm.com/docs/vpc?topic=vpc-client-to-site-authentication

Needs amending in the light of the introduction of secrets-manager and the deprecation of certificate-manager

**Comment by austinmama** [comment]
Hi Andrew.  I have VPN documentation staged for when the client-to-site beta goes live (GA).  It includes a deprecation notice for CM in Sept and the UI is also upgraded with notices, etc.   However, for now, the client-to-site beta UI only includes CM and CRN choices. 
![image](https://user-images.githubusercontent.com/29232369/166509867-1f738cf3-b075-41cc-aabe-0ea2e83133c9.png)

We aren't publicizing the deprecation notice for certificate manager since the pricing plan for Secrets Manager is quite different than CM (free) right now.   https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-migrate-from-certificate-manager

Offering mgmt is still working through the migration to Secrets Mgr for VPN, DNS Services, Application Load Balancer, and CIS.  

Going to close this issue since the docs are currently in the works w/ a consistent message in the UI.  Agree that deprecation notices need to go out soon since Sept. will be upon us shortly, but until the UI is updated, the documentation cannot be published.

I appreciate your feedback.  Just wanted you to understand why it's not updated yet.
