### ISSUE TITLE
About IP spoofing checks

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/vpc#150]
https://cloud.ibm.com/docs/vpc?topic=vpc-ip-spoofing-about

The second part "Enabling IP spoofing checks" is clear so I understand a role as to be granted via IAM.

Regarding the first part
* I see that IP spoofing can be turned on/of at the network adapter level
* I understand if IP-spoofing is on a next hop is evaluated for incoming traffic

What is unclear to me is the first part:
* How is the graphics related to the text showing a successful and unsuccessful spoofing check?
* I do not see that you can allow spoofing for incoming or outgoing traffc only, it seems to be only a switch to turn on or off
* Can the spoofing checks be configured?

**Comment by smikulcik** [comment]
Hey @tschrenk-corp, thanks for filing an issue.

> How is the graphics related to the text showing a successful and unsuccessful spoofing check?

There are 2 types of spoofing checks: source and destination checks.

The destination check is phrased like this:

> Traffic is dropped if its destination address does not match the selected network interface address.

You can see in the unsuccessful diagram how the destination of an incoming packet is `xxx.7`, but the primary address on the network interface is `xxx.5`. Since they don't match, the check fails.

On the successful diagram you can see how the incoming packet has a destination of `xxx.5` just as the network interface does. Since they match, the check succeeds.

We see these use cases for these types of "mismatch addresses" when we do network appliance type instances. A VPN for instance would be routed traffic to it's single IP address with the destination of whatever targets it provides. Inbound packets will have destination of the remote targets. Outbound packets will have the source of the remote target's response. The VPN itself will need to let these mismatched packets flow through with "spoofed" IPs. But you can see also how with request response pairs, typically we will want to disable both source and destination IP spoofing checks together.

I'd be curious to hear if you have use cases for inbound-only or oubound-only IP spoofing checks. Keep in mind that these are NOT stateful rules.
