### ISSUE TITLE
Document the exact type of traffic captured by Flow logs

### ISSUE THREAD

**Issue by tommyk-enablement** [ibm-cloud-docs/vpc#37]
I could not find details about exactly what type of traffic we could capture in the log collector, Do you happen to know the exact type of network traffic we can expect to capture? Along the lines of icmp, or upd, or tcp, ... and etc. I can see ssh and tcp 

If possible, please update the documentation so that we can determine if flow log can capture the traffic we want but also know what we may want to exclude.

**Comment by austinmama** [comment]
@tommyk-enablement  Is this what you are looking for?  [https://cloud.ibm.com/docs/vpc?topic=vpc-fl-analyze#flow-log-data-format](url)

**Comment by tommyk-enablement** [comment]
@austinmama thnx for your response. unfortunately not, we were trying to understand the type of traffice. 
From Andy B's response to me with Pankaj, we are collecting TCP and UDP traffic but not ICMP traffic. 
However the log format spec info helps but adding in the above would provide a more complete understanding.

**Comment by austinmama** [comment]
Hi Tommy,   Andy B agrees with you.  I will add the statement.  FYI... There is no technical limitation to collecting ICMP. It's just not part of the beta because "these flows generate more metadata than the actual flow." It might be considered in a follow-on proposal.  

Thanks for all your feedback in the Slack channel & documentation.

**Comment by austinmama** [comment]
Note added: https://cloud.ibm.com/docs/vpc?topic=vpc-fl-analyze

Please close.  Thanks again!
